language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_success:
  - coveralls
