language: python
sudo: false
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}
after_success:
  - coveralls
services:
  - redis-server
